
X=[
	'bbrgDate datetime NOT NULL',
	'bbrgTime char (8) NOT NULL',
	'bbrgStatus char(20) NOT NULL',
	'bbrgSend6  char(1) NOT NULL',
	'bbrgSend14 char(1) NOT NULL',
	'bbrgRectype char(2) NOT NULL',
	'bbrgSource char(7) NOT NULL',
	'bbrgSectype char(1) NOT NULL',
	'bbrgSec6id char(12) NOT NULL',
	'bbrgInstance char(2) NOT NULL',
	'bbrgTrana char(1) NOT NULL',
	'bbrgConda char(1) NOT NULL',
	'bbrgVala char(14) NOT NULL',
	'bbrgTranb char(1) NOT NULL',
	'bbrgCondb char(1) NOT NULL',
	'bbrgValb char(14) NOT NULL',
	'bbrgTranc char(1) NOT NULL',
	'bbrgCondc char(1) NOT NULL',
	'bbrgValc char(14) NOT NULL',
	'bbrgTrand char(1) NOT NULL',
	'bbrgCondd char(1) NOT NULL',
	'bbrgVald char(14) NOT NULL',
	'bbrgTrane char(1) NOT NULL',
	'bbrgConde char(1) NOT NULL',
	'bbrgVale char(14) NOT NULL',
	'bbrgTranf char(1) NOT NULL',
	'bbrgCondf char(1) NOT NULL',
	'bbrgValf char(14) NOT NULL',
	'bbrgTrang char(1) NOT NULL',
	'bbrgCondg char(1) NOT NULL',
	'bbrgValg char(14) NOT NULL',
	'bbrgTranh char(1) NOT NULL',
	'bbrgCondh char(1) NOT NULL',
	'bbrgValh char(14) NOT NULL',
	'bbrgTrani char(1) NOT NULL',
	'bbrgCondi char(1) NOT NULL',
	'bbrgVali char(14) NOT NULL',
	'bbrgTranj char(1) NOT NULL',
	'bbrgCondj char(1) NOT NULL',
	'bbrgValj char(14) NOT NULL',
	'bbrgTrank char(1) NOT NULL',
	'bbrgCondk char(1) NOT NULL',
	'bbrgValk char(14) NOT NULL',
	'bbrgTranl char(1) NOT NULL',
	'bbrgCondl char(1) NOT NULL',
	'bbrgVall char(14) NOT NULL',
	'bbrgOddlot char(1) NOT NULL',
	'bbrgCcyflag char(1) NOT NULL',
	'bbrgSourceid char(7) NOT NULL',
	'bbrgAcctype char(2) NOT NULL',
	'bbrgSec14id char(12) NOT NULL',
	'bbrgSecshrt char(14) NOT NULL',
	'bbrgAccbm char(2) NOT NULL',
	'bbrgBmsecid char(12) NOT NULL',
	'bbrgBmdesc char(20) NOT NULL',
	'bbrgFunct char(4) NOT NULL',
	'bbrgMonid char(4) NOT NULL',
	'bbrgLdind char(1) NOT NULL',
	'bbrgAmdind char(1) NOT NULL',
	'bbrgFrcol char(2) NOT NULL',
	'bbrgLdtype char(2) NOT NULL',
	'bbrgAbspg char(4) NOT NULL',
	'bbrgMono char(4) NOT NULL',
	'bbrgMonpg char(4) NOT NULL',
	'bbrgOveride char(1) NOT NULL',
	'bbrgCmnt char(30) NOT NULL',
	'bbrgRow char(2) NOT NULL',
	'bbrgRsrv char(2) NOT NULL',
	'bbrgPackid char(2) NOT NULL',
	'bbrgYlwky char(1) NOT NULL',
	'bbrgSprice char(1) NOT NULL',
	'bbrgR2srv char(2) NOT NULL',
	'bbrgTmstamp timestamp NOT NULL',
	'bbrgSysnm char (10) NULL',
    'bbrgUsernm char (20) NULL',
    'bbrgOrigMonid char(4) NULL',
    'bbrgOrigMono char(4) NULL',
    'bbrgOrigAbsPg char(4) NULL',
    'bbrgOrigRow char(2) NULL',
    'bbrgLevel varchar(2) NULL'		
]
